version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4019
      POSTGRES_DB: go_notes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_DSN: postgres://postgres:4019@postgres:5432/go_notes?sslmode=disable
      HTTP_PORT: 8080
      JWT_SECRET: supersecretkey

volumes:
  pgdata: